version: "3.8"

services:

  duckdb:
    container_name: duckdb:latest
    image: duckdb:latest
    restart: always
    profiles: ["base"]
    tty: true
    networks:
      - overturemaps-network
    volumes:
      - ./data/base:/duckdb/data

  overturemaps:
    container_name: overturemaps:latest
    image: overturemaps:latest
    restart: always
    profiles: ["all"]
    tty: true
    command:
      - /duckdb/runsql.sh
    networks:
      - overturemaps-network
    volumes:
      - ./data/all/base:/duckdb/data

  overturemaps-archeo:
    container_name: overturemaps-archeo:latest
    image: overturemaps-archeo:latest
    restart: always
    profiles: ["archeo"]
    tty: true
    command:
      - /duckdb/runsql.sh
    networks:
      - overturemaps-network
    volumes:
      - ./data/archeo:/duckdb/data

  overturemaps-download:
    container_name: overturemaps-downalod:latest
    image: ghcr.io/youssef-harby/overturemapsdownloader:latest
    profiles: ["archeo"]
    command: 
      - /duckdb/italy/downloader.sh
    restart: unless-stopped
    networks:
      - overturemaps-network
    ports:
      - 8888:8888
    volumes:
      - ./data/italy:/duckdb/italy
    
networks:
  overturemaps-network:
    name: overturemaps
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/24

volumes:
  db:
    driver: local